### ISSUE TITLE
Clarify incomplete or unclear requirements for commands

### ISSUE THREAD

**Issue by astrogeco** [nasa/MM#32]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/MD/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [README file](https://github.com/nasa/MD/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
Some requirements are unclear or derive their meaning from the parent requirement

**Describe the solution you'd like**
In general, rewrite ALL requirements in EARS format. 

**Describe alternatives you've considered**
Fix a small subset of requirements, specifically 

| Number | New Text |
| --- | --- |
| MM2000 | When MM receives a Poke command, MM shall write the command-specified number of bits of data to the command-specified RAM address.
| MM2000.1 | When MM writes data to RAM, MM shall generate an event message containing the following data: <br />1. address written; <br />2. length of data written; <br />3. value of the data written |
| *NEW* **MM2000.2** | When MM receives a Poke command, if the data size is not 8, 16, or 32 bits, MM shall reject the command. |
| MM2002 | When MM receives a Peek command, MM shall read the command-specified number of bits of data from the command-specified RAM address and generate an event message containing the following data: <br /> 1. address read; <br /> 2. length of data read; <br /> 3. value of the data read
| MM2003 | When MM receives a “Write With Interrupts Disabled” command, MM shall write up to a compile-time-specified number of bytes to the command-specified RAM memory address with interrupts disabled. | 
| MM2003.1 | When MM receives a “Write with Interrupts Disabled” command, MM shall verify that the command-specified CRC matches the computed CRC of the data. |
| MM2003.2 | When MM receives a “Write with Interrupts Disabled” command, If the command-specified CRC fails validation, MM shall reject the command. |
| MM2004 | When MM receives a “Dump to Event” command, MM shall read the command-specified number of consecutive bytes from the command-specified RAM memory address and generate an event message containing the data. |
| MM2004.1 | When MM receives a “Dump to Event” command, if the number of bytes exceeds the maximum event message size then the command shall be rejected. |
| MM2100.1 | When MM receives a “Load From File” command, If the CRC contained in the command-specified file fails validation, MM shall reject the command. |

**Additional context**
None

**Requester Info**
Gerardo E. Cruz-Ortiz | NASA

**Comment by astrogeco** [comment]
@skliper here's the changes I was proposing

**Comment by skliper** [comment]
@astrogeco Awesome, thanks!  All good suggestions but I recommend we table these until we've got time to think :)

**Comment by skliper** [comment]
Note it seems these got updated in JIRA but not officially approved/accepted (or updated in .csv).  I'll submit a PR with the changes, but they need to finish the process (will likely show up in RC2 requirements document).
