### ISSUE TITLE
Revert PR #52

### ISSUE THREAD

**Issue by dzbaker** [nasa/MM#77]
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/MD/blob/main/CONTRIBUTING.md).
* [X] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
The changes included in PR #52 introduce bugs. We will revert the PR for this release, then revisit it following release.

**Reporter Info**
Dylan Z. Baker - NASA/GSFC

**Comment by skliper** [comment]
@dzbaker - what were the bugs?  Documented anywhere?
